import assert from 'node:assert/strict';
import { after, afterEach, before, beforeEach, test } from 'node:test';
import http from 'node:http';
import type { AddressInfo } from 'node:net';
import { randomUUID } from 'node:crypto';
const databaseUrl=process.env.DATABASE_URL;if(!databaseUrl)throw new Error('Use npm run test:e2e');const runId=process.env.E2E_RUN_ID;if(!runId)throw new Error('E2E runner ownership missing');
const { createApp }=require('../src/app') as typeof import('../src/app');const { prisma }=require('../src/database/prisma') as typeof import('../src/database/prisma');const { signToken }=require('../src/shared/utils/jwt') as typeof import('../src/shared/utils/jwt');const { encryptEvp }=require('../src/modules/directPix/evpKey.crypto') as typeof import('../src/modules/directPix/evpKey.crypto');
let server:http.Server;let baseUrl:string;let n=0;const evp='00000000-0000-0000-0000-000000000001';
async function clean(){const rows=await prisma.$queryRaw<Array<{tablename:string}>>`SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename NOT IN ('_prisma_migrations','_e2e_runner')`;await prisma.$executeRawUnsafe('TRUNCATE TABLE '+rows.map(x=>'"'+x.tablename+'"').join(', ')+' RESTART IDENTITY CASCADE');}
async function setup(){const donor=await prisma.user.create({data:{name:'Donor',email:'donor-'+ ++n+'@test.local',role:'donor',emailVerifiedAt:new Date()}});const owner=await prisma.user.create({data:{name:'Entity',email:'entity-'+n+'@test.local',role:'entity',emailVerifiedAt:new Date()}});const entity=await prisma.entity.create({data:{userId:owner.id,name:'Entity',cnpj:String(n).padStart(14,'0'),responsibleName:'Entity',email:owner.email,status:'active'}});const responsible=await prisma.user.create({data:{name:'Maria Silva',email:'resp-'+n+'@test.local',role:'beneficiary',emailVerifiedAt:new Date()}});const family=await prisma.family.create({data:{entityId:entity.id,responsibleName:responsible.name,displayName:'Família',city:'São Paulo',state:'SP',approvalStatus:'approved'}});const assignment=await prisma.familyResponsibleAssignment.create({data:{familyId:family.id,responsibleUserId:responsible.id,invitedByUserId:owner.id}});const keyId=randomUUID();const sealed=encryptEvp(evp,{recordId:keyId,familyId:family.id,assignmentId:assignment.id,version:1});await prisma.directPixEvpKeyVersion.create({data:{id:keyId,familyId:family.id,assignmentId:assignment.id,submittedByUserId:responsible.id,version:1,status:'ACTIVE',...sealed}});const terms=await prisma.directPixTermsVersion.create({data:{version:'v'+n,title:'Terms',statements:['x'],publishedAt:new Date(),effectiveAt:new Date(),isCurrent:true}});await prisma.directPixTermsAcceptance.create({data:{termsVersionId:terms.id,version:terms.version,actorUserId:donor.id,actorRole:'donor',channel:'test',correlationId:randomUUID()}});for(const key of ['CREATION','DISCLOSURE'] as const)await prisma.directPixFeatureFlag.create({data:{key,scope:'GLOBAL',enabled:true,updatedByUserId:owner.id}});return {donor,family};}
function auth(id:string){return signToken({sub:id,role:'donor',sv:0});}function post(token:string,path:string,body:unknown,key:string){return fetch(baseUrl+path,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json','Idempotency-Key':key},body:JSON.stringify(body)});}
before(async()=>assert.equal((await prisma.$queryRaw<Array<{run_id:string}>>`SELECT run_id FROM "_e2e_runner"`)[0].run_id,runId));beforeEach(async()=>{await clean();await new Promise<void>(r=>{server=createApp().listen(0,'127.0.0.1',r)});baseUrl='http://127.0.0.1:'+(server.address() as AddressInfo).port;});afterEach(async()=>new Promise<void>((r,j)=>server.close(e=>e?j(e):r())));after(async()=>prisma.$disconnect());
test('intent, 256-bit hash-only disclosure, BR Code and declared-send freeze coexist as separate aggregates',async()=>{const x=await setup();const t=auth(x.donor.id);const created=await post(t,'/direct-pix/intents',{familyId:x.family.id,amountCents:5000},'intent-key-0001');assert.equal(created.status,201);const body=await created.json() as {intent:{id:string}};const replay=await post(t,'/direct-pix/intents',{familyId:x.family.id,amountCents:5000},'intent-key-0001');assert.equal(replay.headers.get('idempotency-replayed'),'true');const grant=await post(t,'/direct-pix/intents/'+body.intent.id+'/disclosure-grants',{},'unused');assert.equal(grant.status,201);assert.equal(grant.headers.get('cache-control'),'no-store');const g=await grant.json() as {token:string;expiresAt:string};assert.equal(Buffer.from(g.token,'base64url').length,32);const row=await prisma.pixDisclosureGrant.findFirstOrThrow();assert.notEqual(row.tokenHash,g.token);assert.equal(row.tokenHash.length,64);const disclosure=await fetch(baseUrl+'/direct-pix/intents/'+body.intent.id+'/disclosure',{headers:{authorization:'Bearer '+t,'X-Disclosure-Token':g.token}});assert.equal(disclosure.status,200);assert.equal(disclosure.headers.get('cache-control'),'no-store');const revealed=await disclosure.json() as {brCode:{payload:string;amountCents:number}};assert.equal(revealed.brCode.amountCents,5000);assert.match(revealed.brCode.payload,/6304[0-9A-F]{4}$/);assert.equal(JSON.stringify(await prisma.directPixIntent.findMany()).includes(revealed.brCode.payload),false);const declaration=await post(t,'/direct-pix/intents/'+body.intent.id+'/declaration',{},'declare-key-0001');assert.equal(declaration.status,201);assert.equal((await declaration.json() as {declaration:{status:string}}).declaration.status,'IN_PROGRESS');const intent=await prisma.directPixIntent.findUniqueOrThrow({where:{id:body.intent.id}});assert.equal(intent.status,'DONOR_DECLARED');assert.ok(intent.confirmationDeadlineAt);assert.equal(Math.round(intent.confirmationDeadlineAt!.getTime()-intent.declaredAt!.getTime()),172800000);assert.equal((await fetch(baseUrl+'/direct-pix/families/'+x.family.id+'/public-projection')).status,200);assert.equal((await (await fetch(baseUrl+'/direct-pix/families/'+x.family.id+'/public-projection')).json() as {availability:string}).availability,'IN_PROGRESS');assert.equal(await prisma.donation.count(),0);assert.equal(await prisma.payment.count(),0);assert.equal((await post(t,'/direct-pix/intents',{familyId:x.family.id,amountCents:5000},'after-block-0001')).status,409);});
