import assert from 'node:assert/strict';
import { after, afterEach, before, beforeEach, test } from 'node:test';
import http from 'node:http';
import type { AddressInfo } from 'node:net';
import { createHash, randomBytes } from 'node:crypto';

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error('E2E requires DATABASE_URL from the root Docker Compose runner. Use: npm run test:e2e');
const runId = process.env.E2E_RUN_ID;
if (!runId || !/^mealfy-e2e-[a-zA-Z0-9-]+$/.test(runId)) throw new Error('E2E requires the ownership token created by the root Docker Compose runner.');
const parsed = new URL(databaseUrl);
if (process.env.NODE_ENV !== 'test' || parsed.hostname !== '127.0.0.1' || parsed.pathname !== '/mealfy_e2e') throw new Error('Refusing to run E2E outside the isolated local PostgreSQL database mealfy_e2e on 127.0.0.1.');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { createApp } = require('../src/app') as typeof import('../src/app');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { prisma } = require('../src/database/prisma') as typeof import('../src/database/prisma');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { signToken } = require('../src/shared/utils/jwt') as typeof import('../src/shared/utils/jwt');

let server: http.Server | undefined;
let baseUrl: string;
const evp = '00000000-0000-0000-0000-000000000001';
const permissions = ['operators.manage', 'families.read', 'families.write', 'pix.submit', 'pix.review', 'pix.follow_up', 'audit.read'];

async function cleanDatabase() { const rows = await prisma.$queryRaw<Array<{ tablename: string }>>`SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename NOT IN ('_prisma_migrations', '_e2e_runner')`; await prisma.$executeRawUnsafe('TRUNCATE TABLE ' + rows.map(({ tablename }) => '"' + tablename + '"').join(', ') + ' RESTART IDENTITY CASCADE'); }
async function createEntity(suffix: string, granted = permissions) { const user = await prisma.user.create({ data: { name: 'Operator ' + suffix, email: 'operator-' + suffix + '@example.test', role: 'entity', status: 'active', emailVerifiedAt: new Date() } }); const entity = await prisma.entity.create({ data: { userId: user.id, name: 'Entity ' + suffix, cnpj: suffix.padStart(14, '0'), responsibleName: user.name, email: user.email, status: 'active' } }); await prisma.entityOperatorMembership.create({ data: { entityId: entity.id, userId: user.id, permissions: granted } }); return { user, entity, token: signToken({ sub: user.id, role: 'entity', sv: user.sessionVersion }) }; }
async function createResponsible(suffix: string) { const user = await prisma.user.create({ data: { name: 'Responsible ' + suffix, email: 'responsible-' + suffix + '@example.test', role: 'beneficiary', status: 'active', emailVerifiedAt: new Date(), passwordHash: 'not-used' } }); return { user, token: signToken({ sub: user.id, role: 'beneficiary', sv: user.sessionVersion }) }; }
async function createFamily(entityId: string, responsibleId: string) { const family = await prisma.family.create({ data: { responsibleName: 'Responsible', displayName: 'Family', entityId, city: 'São Paulo', state: 'SP', approvalStatus: 'approved' } }); const assignment = await prisma.familyResponsibleAssignment.create({ data: { familyId: family.id, responsibleUserId: responsibleId, invitedByUserId: responsibleId } }); return { family, assignment }; }
async function proof(userId: string, familyId: string) { const raw = randomBytes(32).toString('base64url'); await prisma.stepUpAuthorization.create({ data: { userId, purpose: 'change_pix_key', resourceId: familyId, tokenHash: createHash('sha256').update(raw + ':' + process.env.JWT_SECRET).digest('hex'), sessionVersion: 0, expiresAt: new Date(Date.now() + 60_000) } }); return raw; }
function assistedSubmit(token: string, familyId: string, key = 'assisted-submit-idempotency') { return fetch(baseUrl + '/direct-pix/families/' + familyId + '/assisted-evp-key-versions', { method: 'POST', headers: { authorization: 'Bearer ' + token, 'content-type': 'application/json', 'idempotency-key': key }, body: JSON.stringify({ keyType: 'EVP', evp }) }); }
function confirm(token: string, versionId: string, authorization: string, key = 'assisted-confirm-idempotency') { return fetch(baseUrl + '/direct-pix/responsible/evp-key-versions/' + versionId + '/confirm-assisted', { method: 'POST', headers: { authorization: 'Bearer ' + token, 'content-type': 'application/json', 'idempotency-key': key, 'x-step-up-authorization': authorization }, body: JSON.stringify({}) }); }

before(async () => { assert.deepEqual(await prisma.$queryRaw<Array<{ run_id: string; database: string }>>`SELECT run_id,current_database() AS database FROM "_e2e_runner"`, [{ run_id: runId, database: 'mealfy_e2e' }]); });
beforeEach(async () => { await cleanDatabase(); await new Promise<void>((resolve) => { server = createApp().listen(0, '127.0.0.1', resolve); }); baseUrl = 'http://127.0.0.1:' + (server!.address() as AddressInfo).port; });
afterEach(async () => { if (server) await new Promise<void>((resolve, reject) => server!.close((error) => error ? reject(error) : resolve())); });
after(async () => prisma.$disconnect());

test('entity submits only in its own scope and active responsible sees a masked awaiting version', async () => { const owner = await createEntity('001'); const foreign = await createEntity('002'); const responsible = await createResponsible('001'); const { family } = await createFamily(owner.entity.id, responsible.user.id); const foreignResponse = await assistedSubmit(foreign.token, family.id, 'foreign-entity-key'); assert.equal(foreignResponse.status, 404); const accepted = await assistedSubmit(owner.token, family.id); assert.equal(accepted.status, 201); const body = await accepted.json() as { keyVersion: { id: string; status: string; evpMasked: string; submittedByEntity: { id: string; name: string } } }; assert.equal(body.keyVersion.status, 'AWAITING_RESPONSIBLE_CONFIRMATION'); assert.equal(body.keyVersion.submittedByEntity.id, owner.entity.id); assert.doesNotMatch(JSON.stringify(body), new RegExp(evp)); const pending = await fetch(baseUrl + '/direct-pix/responsible/assisted-evp-key-versions', { headers: { authorization: 'Bearer ' + responsible.token } }); assert.equal(pending.status, 200); const list = await pending.json() as { keyVersions: Array<{ id: string; evpMasked: string; submittedByEntity: { name: string } }> }; assert.deepEqual(list.keyVersions.map(x => x.id), [body.keyVersion.id]); assert.match(list.keyVersions[0].evpMasked, /^••••/); assert.equal(list.keyVersions[0].submittedByEntity.name, owner.entity.name); assert.equal(await prisma.directPixOperatorAction.count({ where: { resourceId: body.keyVersion.id, action: 'submit' } }), 1); });

test('only current responsible can step-up confirm and transition to pending review', async () => { const owner = await createEntity('003'); const responsible = await createResponsible('003'); const other = await createResponsible('other'); const { family } = await createFamily(owner.entity.id, responsible.user.id); const submitted = await assistedSubmit(owner.token, family.id, 'confirm-target'); const { keyVersion } = await submitted.json() as { keyVersion: { id: string } }; const operatorProof = await proof(owner.user.id, family.id); assert.equal((await confirm(owner.token, keyVersion.id, operatorProof, 'operator-confirm')).status, 403); const otherProof = await proof(other.user.id, family.id); assert.equal((await confirm(other.token, keyVersion.id, otherProof, 'other-confirm')).status, 403); const valid = await proof(responsible.user.id, family.id); const confirmed = await confirm(responsible.token, keyVersion.id, valid); assert.equal(confirmed.status, 200); const body = await confirmed.json() as { keyVersion: { status: string } }; assert.equal(body.keyVersion.status, 'PENDING_REVIEW'); const actions = await prisma.auditLog.findMany({ where: { entityId: keyVersion.id }, orderBy: { createdAt: 'asc' } }); assert.equal(actions.length, 2); assert.doesNotMatch(JSON.stringify(actions), new RegExp(evp)); assert.equal(await prisma.outboxEvent.count({ where: { aggregateId: keyVersion.id } }), 2); });

test('replay and concurrent confirmation produce one transition, audit, and outbox', async () => { const owner = await createEntity('004'); const responsible = await createResponsible('004'); const { family } = await createFamily(owner.entity.id, responsible.user.id); const [first, replay] = await Promise.all([assistedSubmit(owner.token, family.id, 'assisted-race-submit'), assistedSubmit(owner.token, family.id, 'assisted-race-submit')]); assert.deepEqual([first.status, replay.status].sort(), [201, 201]); assert.equal(await prisma.directPixEvpKeyVersion.count(), 1); const version = await prisma.directPixEvpKeyVersion.findFirstOrThrow(); const p = await proof(responsible.user.id, family.id); const [a, b] = await Promise.all([confirm(responsible.token, version.id, p, 'assisted-race-confirm'), confirm(responsible.token, version.id, p, 'assisted-race-confirm')]); assert.deepEqual([a.status, b.status].sort(), [200, 200]); assert.equal(await prisma.auditLog.count({ where: { entityId: version.id, action: 'direct_pix.evp.assisted_confirmed' } }), 1); assert.equal(await prisma.outboxEvent.count({ where: { aggregateId: version.id, eventType: 'direct_pix.evp.assisted_confirmed' } }), 1); const stale = await confirm(responsible.token, version.id, await proof(responsible.user.id, family.id), 'confirm-after-transition'); assert.equal(stale.status, 409); });

test('assignment changed before confirmation is rejected inside the transaction', async () => { const owner = await createEntity('005'); const former = await createResponsible('former'); const replacement = await createResponsible('replacement'); const { family, assignment } = await createFamily(owner.entity.id, former.user.id); const submitted = await assistedSubmit(owner.token, family.id, 'changed-assignment-submit'); const { keyVersion } = await submitted.json() as { keyVersion: { id: string } }; await prisma.familyResponsibleAssignment.update({ where: { id: assignment.id }, data: { endedAt: new Date(), endReason: 'reassigned' } }); await prisma.familyResponsibleAssignment.create({ data: { familyId: family.id, responsibleUserId: replacement.user.id, invitedByUserId: replacement.user.id } }); const p = await proof(former.user.id, family.id); const rejected = await confirm(former.token, keyVersion.id, p, 'former-after-reassignment'); assert.equal(rejected.status, 403); assert.equal((await prisma.directPixEvpKeyVersion.findUniqueOrThrow({ where: { id: keyVersion.id } })).status, 'AWAITING_RESPONSIBLE_CONFIRMATION'); assert.equal(await prisma.auditLog.count({ where: { entityId: keyVersion.id, action: 'direct_pix.evp.assisted_confirmed' } }), 0); });
