import assert from 'node:assert/strict';
import { after, afterEach, before, beforeEach, test } from 'node:test';
import http from 'node:http';
import type { AddressInfo } from 'node:net';
import { randomBytes, randomUUID } from 'node:crypto';

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) throw new Error('E2E requires DATABASE_URL from the root Docker Compose runner. Use: npm run test:e2e');
const runId = process.env.E2E_RUN_ID;
if (!runId || !/^mealfy-e2e-[a-zA-Z0-9-]+$/.test(runId)) throw new Error('E2E requires the ownership token created by the root Docker Compose runner.');
const parsed = new URL(databaseUrl);
if (process.env.NODE_ENV !== 'test' || parsed.hostname !== '127.0.0.1' || parsed.pathname !== '/mealfy_e2e') throw new Error('Refusing to run E2E outside isolated PostgreSQL.');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { createApp } = require('../src/app') as typeof import('../src/app');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { prisma } = require('../src/database/prisma') as typeof import('../src/database/prisma');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { signToken } = require('../src/shared/utils/jwt') as typeof import('../src/shared/utils/jwt');
let server: http.Server | undefined; let baseUrl = ''; let n = 0;
async function clean() { const tables = await prisma.$queryRaw<Array<{ tablename: string }>>`SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename NOT IN ('_prisma_migrations', '_e2e_runner')`; await prisma.$executeRawUnsafe('TRUNCATE TABLE ' + tables.map((x) => '"' + x.tablename + '"').join(', ') + ' RESTART IDENTITY CASCADE'); }
function token(user: { id: string; role: string }) { return signToken({ sub: user.id, role: user.role as 'donor' | 'entity' | 'beneficiary' | 'admin', sv: 0 }); }
async function user(role: 'donor' | 'entity' | 'beneficiary', name: string) { const i = ++n; return prisma.user.create({ data: { name, email: name.toLowerCase().replaceAll(' ', '-') + i + '@example.test', role, status: 'active', emailVerifiedAt: new Date(), passwordHash: '$2a$10$ThisIsNotUsedByResponseTests000000000000000000000000000000000' } }); }
async function fixture() {
 const owner = await user('entity', 'Owner'); const entity = await prisma.entity.create({ data: { userId: owner.id, name: 'Entity', cnpj: String(++n).padStart(14, '0'), responsibleName: owner.name, email: owner.email, status: 'active' } });
 const operator = await user('entity', 'Operator'); await prisma.entityOperatorMembership.create({ data: { entityId: entity.id, userId: operator.id, permissions: ['pix.follow_up'] } });
 const otherEntityOwner = await user('entity', 'Other Owner'); const otherEntity = await prisma.entity.create({ data: { userId: otherEntityOwner.id, name: 'Other entity', cnpj: String(++n).padStart(14, '0'), responsibleName: otherEntityOwner.name, email: otherEntityOwner.email, status: 'active' } });
 const otherOperator = await user('entity', 'Other Operator'); await prisma.entityOperatorMembership.create({ data: { entityId: otherEntity.id, userId: otherOperator.id, permissions: ['pix.follow_up'] } });
 const donor = await user('donor', 'Donor'); const responsible = await user('beneficiary', 'Responsible'); const family = await prisma.family.create({ data: { entityId: entity.id, responsibleName: responsible.name, displayName: 'Family', city: 'São Paulo', state: 'SP', approvalStatus: 'approved' } });
 const assignment = await prisma.familyResponsibleAssignment.create({ data: { familyId: family.id, responsibleUserId: responsible.id, invitedByUserId: owner.id } });
 const key = await prisma.directPixEvpKeyVersion.create({ data: { id: randomUUID(), familyId: family.id, assignmentId: assignment.id, submittedByUserId: responsible.id, version: 1, status: 'ACTIVE', encryptionKid: 'e2e-aes-2026-01', nonce: 'AAAAAAAAAAAAAAAA', ciphertext: 'AA', tag: 'AAAAAAAAAAAAAAAAAAAAAA', fingerprintKid: 'e2e-hmac-2026-01', fingerprint: 'fp-' + ++n } });
 async function intent() { const now = new Date(); const row = await prisma.directPixIntent.create({ data: { donorId: donor.id, familyId: family.id, responsibleAssignmentId: assignment.id, pixKeyVersionId: key.id, amountCents: 5000, txid: randomUUID().replaceAll('-', '').slice(0,25), status: 'DONOR_DECLARED', cycleStartAt: now, cycleEndAt: new Date(now.getTime()+86400000), declarationDeadlineAt: new Date(now.getTime()+86400000), declaredAt: now, confirmationDeadlineAt: new Date(now.getTime()+172800000) } }); await prisma.directPixDeclaration.create({ data: { intentId: row.id, declaredByUserId: donor.id } }); return row; }
 return { donor, responsible, operator, otherOperator, family, assignment, intent };
}
function post(auth: string, path: string, body: unknown, key: string, extra: Record<string,string> = {}) { return fetch(baseUrl + path, { method: 'POST', headers: { authorization: 'Bearer ' + auth, 'content-type': 'application/json', 'idempotency-key': key, ...extra }, body: JSON.stringify(body) }); }
async function responseStepUp(userId: string, intentId: string) { const raw = randomBytes(32).toString('base64url'); const { createHash } = await import('node:crypto'); const digest = createHash('sha256').update(raw + ':mealfy-e2e-isolated-secret').digest('hex'); await prisma.stepUpAuthorization.create({ data: { userId, purpose: 'confirm_direct_pix_receipt', resourceId: intentId, tokenHash: digest, sessionVersion: 0, expiresAt: new Date(Date.now()+600000) } }); return raw; }
before(async()=>assert.deepEqual(await prisma.$queryRaw<Array<{run_id:string;database:string}>>`SELECT run_id,current_database() AS database FROM "_e2e_runner"`,[{run_id:runId,database:'mealfy_e2e'}]));
beforeEach(async()=>{await clean();await new Promise<void>((resolve)=>{server=createApp().listen(0,'127.0.0.1',resolve);});baseUrl='http://127.0.0.1:'+((server!.address() as AddressInfo).port);});
afterEach(async()=>{if(server)await new Promise<void>((resolve,reject)=>server!.close((e)=>e?reject(e):resolve()));});after(async()=>prisma.$disconnect());

test('donor can cancel only own unreplied declaration with atomic audit/outbox and idempotent replay',async()=>{const x=await fixture();const i=await x.intent();const path='/direct-pix/intents/'+i.id+'/cancel-declaration';const key='cancel-response-key';const first=await post(token(x.donor),path,{reason:'TRANSFER_NOT_SENT'},key);assert.equal(first.status,201);assert.equal((await first.json() as {intent:{status:string}}).intent.status,'CANCELED_BY_DONOR');const replay=await post(token(x.donor),path,{reason:'TRANSFER_NOT_SENT'},key);assert.equal(replay.status,200);assert.equal(replay.headers.get('idempotency-replayed'),'true');assert.equal(await prisma.directPixDeclarationCancellation.count(),1);assert.equal(await prisma.auditLog.count({where:{action:'direct_pix.declaration.canceled_by_donor'}}),1);assert.equal(await prisma.outboxEvent.count({where:{eventType:'direct_pix.declaration.canceled_by_donor'}}),1);const foreign=await fixture();const forbidden=await post(token(foreign.donor),path,{reason:'TRANSFER_NOT_SENT'},'foreign-cancel');assert.equal(forbidden.status,404);});

test('only exact active responsible with resource-bound step-up can make declaratory exact receipt response',async()=>{const x=await fixture();const i=await x.intent();const missing=await post(token(x.responsible),'/direct-pix/responsible/intents/'+i.id+'/receipt-confirmations',{outcome:'RECEIVED_EXACT'},'exact-missing');assert.equal(missing.status,422);const stepUp=await responseStepUp(x.responsible.id,i.id);const exact=await post(token(x.responsible),'/direct-pix/responsible/intents/'+i.id+'/receipt-confirmations',{outcome:'RECEIVED_EXACT'},'exact-ok',{'X-Step-Up-Authorization':stepUp});assert.equal(exact.status,201);const body=await exact.json() as {intent:{status:string};receipt:{outcome:string}};assert.equal(body.intent.status,'FAMILY_CONFIRMED');assert.equal(body.receipt.outcome,'RECEIVED_EXACT');assert.equal(await prisma.directPixReceiptConfirmation.count(),1);assert.equal(await prisma.donation.count(),0);assert.equal(await prisma.payment.count(),0);assert.equal(await prisma.auditLog.count({where:{action:'direct_pix.receipt.confirmed_by_responsible'}}),1);});

test('entity assisted divergent response preserves declarant/operator and opens segregated follow-up case',async()=>{const x=await fixture();const i=await x.intent();const response=await post(token(x.operator),'/direct-pix/entity/intents/'+i.id+'/assisted-receipt-confirmations',{outcome:'RECEIVED_DIFFERENT',receivedAmountCents:4700,assistedChannel:'IN_PERSON'},'assisted-divergence');assert.equal(response.status,201);const body=await response.json() as {intent:{status:string};receipt:{assisted:boolean};followUpCase:{reason:string}};assert.equal(body.intent.status,'FOLLOW_UP_REQUIRED');assert.equal(body.receipt.assisted,true);assert.equal(body.followUpCase.reason,'RECEIVED_DIFFERENT');const receipt=await prisma.directPixReceiptConfirmation.findUniqueOrThrow({where:{intentId:i.id}});assert.equal(receipt.declaredByResponsibleUserId,x.responsible.id);assert.equal(receipt.recordedByOperatorUserId,x.operator.id);const own=await fetch(baseUrl+'/direct-pix/entity/follow-up-cases',{headers:{authorization:'Bearer '+token(x.operator)}});assert.equal(own.status,200);assert.equal((await own.json() as {cases:unknown[]}).cases.length,1);const foreign=await fetch(baseUrl+'/direct-pix/entity/follow-up-cases',{headers:{authorization:'Bearer '+token(x.otherOperator)}});assert.equal(foreign.status,200);assert.equal((await foreign.json() as {cases:unknown[]}).cases.length,0);assert.equal(await prisma.outboxEvent.count({where:{eventType:'direct_pix.follow_up.opened'}}),1);});

test('not-located assisted response validates shape, creates one case, and cannot be replayed with different body',async()=>{const x=await fixture();const i=await x.intent();const path='/direct-pix/entity/intents/'+i.id+'/assisted-receipt-confirmations';const initial={outcome:'NOT_LOCATED',assistedChannel:'PHONE'};const one=await post(token(x.operator),path,initial,'not-located');assert.equal(one.status,201);const replay=await post(token(x.operator),path,initial,'not-located');assert.equal(replay.status,200);const conflict=await post(token(x.operator),path,{outcome:'RECEIVED_DIFFERENT',receivedAmountCents:1,assistedChannel:'PHONE'},'not-located');assert.equal(conflict.status,409);assert.equal(await prisma.directPixFollowUpCase.count(),1);});
