import { randomUUID } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import nodemailer from 'nodemailer';
import { env } from '../../config/env';
import { AppError } from '../errors/AppError';

function smtpConfigured(): boolean { return Boolean(env.SMTP_HOST && env.SMTP_PORT && env.SMTP_USER && env.SMTP_PASS && env.SMTP_FROM && env.APP_URL); }
function assertMailerConfigured(unavailableMessage: string): void { if (env.EMAIL_DELIVERY_MODE === 'capture' && env.EMAIL_CAPTURE_DIR) return; if (!smtpConfigured()) throw new AppError(unavailableMessage, 503, 'email_not_configured'); }
export function assertPasswordResetMailerConfigured(): void { assertMailerConfigured('Recuperação de senha indisponível no momento.'); }
export function assertEmailVerificationMailerConfigured(): void { assertMailerConfigured('Verificação de e-mail indisponível no momento.'); }
export function assertStepUpMailerConfigured(): void { assertMailerConfigured('Autenticação reforçada indisponível no momento.'); }
function normalizeRecipient(to: string): string | null { if (to.includes('\r') || to.includes('\n') || to.includes(',') || to.includes(';')) return null; const normalized = to.trim().toLowerCase(); return normalized || null; }
function allowedRecipient(to: string): string | null { const normalized = normalizeRecipient(to); if (!normalized) return null; if (env.EMAIL_DELIVERY_MODE !== 'allowlist') return normalized; return (env.EMAIL_ALLOWLIST ?? []).includes(normalized) ? normalized : null; }
async function captureMail(payload: Record<string, unknown>): Promise<void> { const directory = path.resolve(env.EMAIL_CAPTURE_DIR!); await mkdir(directory, { recursive: true, mode: 0o700 }); await writeFile(path.join(directory, randomUUID() + '.json'), JSON.stringify(payload), { encoding: 'utf8', mode: 0o600, flag: 'wx' }); }
async function capturePasswordReset(to: string, resetToken: string): Promise<void> { await captureMail({ kind: 'password_reset', to, resetToken, expiresInMinutes: env.PASSWORD_RESET_TTL_MINUTES }); }
function smtpTransport() { return nodemailer.createTransport({ host: env.SMTP_HOST!, port: env.SMTP_PORT!, secure: env.SMTP_PORT === 465, auth: { user: env.SMTP_USER!, pass: env.SMTP_PASS! }, connectionTimeout: 5_000, greetingTimeout: 5_000, socketTimeout: 10_000 }); }
export async function sendPasswordResetEmail(to: string, resetToken: string): Promise<void> { assertPasswordResetMailerConfigured(); const recipient = allowedRecipient(to); if (!recipient) throw new AppError('Destinatário indisponível neste ambiente.', 503, 'email_recipient_forbidden'); if (env.EMAIL_DELIVERY_MODE === 'capture') { await capturePasswordReset(recipient, resetToken); return; } const url = new URL('/reset-password', env.APP_URL!); url.searchParams.set('token', resetToken); await smtpTransport().sendMail({ from: env.SMTP_FROM!, to: recipient, subject: 'Redefinição de senha Mealfy', text: 'Recebemos uma solicitação para redefinir sua senha. Use este link em até ' + env.PASSWORD_RESET_TTL_MINUTES + ' minutos: ' + url.toString() + '\n\nSe não foi você, ignore esta mensagem.' }); }
export async function sendStepUpCodeEmail(to: string, code: string): Promise<void> { assertStepUpMailerConfigured(); const recipient = allowedRecipient(to); if (!recipient) throw new AppError('Destinatário indisponível neste ambiente.', 503, 'email_recipient_forbidden'); if (env.EMAIL_DELIVERY_MODE === 'capture') { await captureMail({ kind: 'direct_pix_step_up', to: recipient, code, expiresInMinutes: 10 }); return; } await smtpTransport().sendMail({ from: env.SMTP_FROM!, to: recipient, subject: 'Código de segurança do Pix direto', text: `Seu código de segurança Mealfy é ${code}. Ele expira em 10 minutos e só autoriza a ação solicitada. Se não foi você, ignore esta mensagem.` }); }
export async function sendEntityOperatorInvitationEmail(to: string, invitationToken: string): Promise<void> { assertStepUpMailerConfigured(); const recipient = allowedRecipient(to); if (!recipient) throw new AppError('Destinatário indisponível neste ambiente.', 503, 'email_recipient_forbidden'); if (env.EMAIL_DELIVERY_MODE === 'capture') { await captureMail({ kind: 'entity_operator_invitation', to: recipient, invitationToken, expiresInHours: 48 }); return; } const url = new URL('/entity-operator-invitation', env.APP_URL!); url.searchParams.set('token', invitationToken); await smtpTransport().sendMail({ from: env.SMTP_FROM!, to: recipient, subject: 'Convite de operador da entidade Mealfy', text: `Você recebeu um convite para operar uma entidade na Mealfy. Aceite em até 48 horas: ${url.toString()}\n\nSe não esperava este convite, ignore esta mensagem.` }); }
/** A fragment prevents the bearer token from reaching servers, proxies and referrers. */
export async function sendFamilyResponsibleInvitationEmail(to: string, invitationToken: string): Promise<void> { assertStepUpMailerConfigured(); const recipient = allowedRecipient(to); if (!recipient) throw new AppError('Destinatário indisponível neste ambiente.', 503, 'email_recipient_forbidden'); if (env.EMAIL_DELIVERY_MODE === 'capture') { await captureMail({ kind: 'family_responsible_invitation', to: recipient, invitationToken, expiresInHours: 48 }); return; } const url = new URL('/family-responsible-invitation', env.APP_URL!); url.hash = new URLSearchParams({ token: invitationToken }).toString(); await smtpTransport().sendMail({ from: env.SMTP_FROM!, to: recipient, subject: 'Convite para ser responsável familiar na Mealfy', text: `Você recebeu um convite para representar uma família na Mealfy. Aceite em até 48 horas: ${url.toString()}\n\nSe não esperava este convite, ignore esta mensagem.` }); }
export async function sendEmailVerificationEmail(to: string, verificationToken: string): Promise<void> { assertEmailVerificationMailerConfigured(); const recipient = allowedRecipient(to); if (!recipient) throw new AppError('Destinatário indisponível neste ambiente.', 503, 'email_recipient_forbidden'); if (env.EMAIL_DELIVERY_MODE === 'capture') { await captureMail({ kind: 'email_verification', to: recipient, verificationToken, expiresInMinutes: env.EMAIL_VERIFICATION_TTL_MINUTES }); return; } const url = new URL('/verify-email', env.APP_URL!); url.searchParams.set('token', verificationToken); await smtpTransport().sendMail({ from: env.SMTP_FROM!, to: recipient, subject: 'Confirme seu e-mail Mealfy', text: 'Confirme que este e-mail pertence a você usando o link em até ' + env.EMAIL_VERIFICATION_TTL_MINUTES + ' minutos: ' + url.toString() + '\n\nSe não foi você, ignore esta mensagem.' }); }
