// <auto-generated />
using System;
using Mealfy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mealfy.Infrastructure.Migrations
{
    [DbContext(typeof(MealfyDbContext))]
    [Migration("20260610040614_InitialPostgreSql")]
    partial class InitialPostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mealfy.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_EntityType_EntityId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_UserId_CreatedAt");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.AuthorizingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressOrDistrict")
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("WebsiteOrInstagram")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj");

                    b.HasIndex("Email");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.Donation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CommunityId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DonorId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.DonorIndication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChildrenCount")
                        .HasColumnType("integer");

                    b.Property<string>("Contact")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConvertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConvertedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConvertedFamilyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IndicatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConvertedFamilyId")
                        .IsUnique()
                        .HasFilter("\"ConvertedFamilyId\" IS NOT NULL");

                    b.HasIndex("IndicatedByUserId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_Indications_Status_CreatedAt");

                    b.ToTable("Indications");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChildrenCount")
                        .HasColumnType("integer");

                    b.Property<string>("ChildrenNamesJson")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text");

                    b.Property<string>("InternalRef")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<float?>("IvcadScore")
                        .HasColumnType("real");

                    b.Property<DateTime?>("LastFedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("MainNeed")
                        .HasColumnType("text");

                    b.Property<bool>("NeedsEntitySupport")
                        .HasColumnType("boolean");

                    b.Property<string>("Neighborhood")
                        .HasColumnType("text");

                    b.Property<Guid?>("OriginalIndicationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("PriorityLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepresentativeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleCpf")
                        .HasColumnType("text");

                    b.Property<string>("ShortAddress")
                        .HasColumnType("text");

                    b.Property<string>("SourceLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SupportStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByEntityId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.FamilyValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId", "Source")
                        .IsUnique();

                    b.ToTable("FamilyValidations");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.GiftCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DonationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DonorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DonationId")
                        .IsUnique();

                    b.HasIndex("DonorId");

                    b.HasIndex("FamilyId");

                    b.ToTable("GiftCards");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AnonymousMode")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("BeneficiaryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Facebook")
                        .HasColumnType("text");

                    b.Property<string>("FirebaseUid")
                        .HasColumnType("text");

                    b.Property<string>("Instagram")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PreferredRegion")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowInstagram")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowOnRanking")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalDonated")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EntityId");

                    b.HasIndex("FirebaseUid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Mealfy.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.Donation", b =>
                {
                    b.HasOne("Mealfy.Domain.Entities.User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mealfy.Domain.Entities.Family", "Family")
                        .WithMany("Donations")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donor");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.DonorIndication", b =>
                {
                    b.HasOne("Mealfy.Domain.Entities.Family", null)
                        .WithOne()
                        .HasForeignKey("Mealfy.Domain.Entities.DonorIndication", "ConvertedFamilyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mealfy.Domain.Entities.User", "IndicatedByUser")
                        .WithMany()
                        .HasForeignKey("IndicatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IndicatedByUser");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.Family", b =>
                {
                    b.HasOne("Mealfy.Domain.Entities.AuthorizingEntity", "CreatedByEntity")
                        .WithMany("Families")
                        .HasForeignKey("CreatedByEntityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByEntity");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.FamilyValidation", b =>
                {
                    b.HasOne("Mealfy.Domain.Entities.Family", "Family")
                        .WithMany("Validations")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.GiftCard", b =>
                {
                    b.HasOne("Mealfy.Domain.Entities.Donation", "Donation")
                        .WithOne("GiftCard")
                        .HasForeignKey("Mealfy.Domain.Entities.GiftCard", "DonationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mealfy.Domain.Entities.User", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mealfy.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donation");

                    b.Navigation("Donor");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.User", b =>
                {
                    b.HasOne("Mealfy.Domain.Entities.AuthorizingEntity", "Entity")
                        .WithMany("Users")
                        .HasForeignKey("EntityId");

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.AuthorizingEntity", b =>
                {
                    b.Navigation("Families");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.Donation", b =>
                {
                    b.Navigation("GiftCard");
                });

            modelBuilder.Entity("Mealfy.Domain.Entities.Family", b =>
                {
                    b.Navigation("Donations");

                    b.Navigation("Validations");
                });
#pragma warning restore 612, 618
        }
    }
}
