namespace Mealfy.Application.Contracts.Families;

public record FamilyDto(
    string Id,
    string RepresentativeName,
    string Region,
    int ChildrenCount,
    string Status,
    string SupportStatus,
    string SourceType,
    string SourceLabel,
    double Latitude,
    double Longitude,
    string? City,
    string? State,
    string? Neighborhood = null,
    string? ShortAddress = null,
    string? Description = null,
    string? MainNeed = null,
    string? PhotoUrl = null,
    string? FamilyName = null,
    string? ResponsibleName = null,
    string? ResponsibleCpf = null,
    object[]? Children = null,
    bool NeedsEntitySupport = false,
    int PriorityLevel = 3);
