import { createHash, randomBytes } from 'node:crypto';
import { Prisma } from '@prisma/client';
import { prisma } from '../../database/prisma';
import { AppError } from '../../shared/errors/AppError';
import { decryptEvp } from './evpKey.crypto';
import { assertDirectPixCreationAllowed, evaluateDirectPixFeature } from './featureFlags.service';
import { buildStaticBrCode } from './brCode';
import { assertDirectPixAvailable } from './suspension.service';

const TTL = 86400000, GRANT_TTL = 900000;
const intentOperation = 'direct_pix.create_intent', declarationOperation = 'direct_pix.declare_send';
type Tx = Prisma.TransactionClient;
function error(message: string, status: number, code: string): never { throw new AppError(message, status, code); }
function digest(value: unknown) { return createHash('sha256').update(JSON.stringify(value)).digest('hex'); }
function tokenDigest(value: string) { return createHash('sha256').update(value).digest('hex'); }
function newTxid() { return randomBytes(12).toString('hex').toUpperCase(); }
function supportCycle(now: Date) { const p = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo', year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', hourCycle: 'h23' }).formatToParts(now); const get = (type: string) => p.find((x) => x.type === type)!.value; let start = new Date(Date.UTC(Number(get('year')), Number(get('month')) - 1, Number(get('day')), 11)); if (Number(get('hour')) < 8) start = new Date(start.getTime() - 86400000); return { start, end: new Date(start.getTime() + 86400000) }; }
function dto(x: { id:string; familyId:string; amountCents:number; status:string; declarationDeadlineAt:Date; createdAt:Date }) { return { id:x.id, familyId:x.familyId, amountCents:x.amountCents, status:x.status, declarationDeadlineAt:x.declarationDeadlineAt.toISOString(), createdAt:x.createdAt.toISOString() }; }
async function requireTerms(tx: Tx, userId: string) { const terms = await tx.directPixTermsVersion.findFirst({ where: { isCurrent: true, effectiveAt: { lte: new Date() } }, select: { id: true } }); if (!terms || !await tx.directPixTermsAcceptance.findUnique({ where: { actorUserId_termsVersionId: { actorUserId: userId, termsVersionId: terms.id } } })) error('Aceite vigente dos termos do Pix direto é obrigatório.', 403, 'direct_pix_terms_required'); }
async function replay(userId:string, operation:string, key:string, requestHash:string) { const r = await prisma.idempotencyRecord.findUnique({ where: { actorUserId_operation_idempotencyKey: { actorUserId:userId, operation, idempotencyKey:key } } }); if (!r) return null; if (r.requestHash !== requestHash) error('A chave de idempotência já foi usada com outra requisição.',409,'idempotency_conflict'); if (r.status !== 'completed' || !r.resourceId) error('A operação idempotente ainda está em processamento.',409,'idempotency_in_progress'); return r.resourceId; }

export async function createIntent(userId:string, input:{familyId:string;amountCents:number;idempotencyKey:string;correlationId:string}) { const requestHash=digest({familyId:input.familyId,amountCents:input.amountCents}); const previous=await replay(userId,intentOperation,input.idempotencyKey,requestHash); if(previous){const x=await prisma.directPixIntent.findFirst({where:{id:previous,donorId:userId}});if(!x)error('Intenção não encontrada.',404,'intent_not_found');return {intent:dto(x),replayed:true};} const x=await prisma.$transaction(async tx=>{const family=await tx.family.findUnique({where:{id:input.familyId},select:{id:true,entityId:true,approvalStatus:true}});if(!family||family.approvalStatus!=='approved')error('Família indisponível para Pix direto.',404,'family_not_available');await assertDirectPixCreationAllowed(family.id,family.entityId,tx);await tx.$executeRawUnsafe('SELECT pg_advisory_xact_lock(hashtext($1))','direct-pix-family:'+family.id);await requireTerms(tx,userId);if(await tx.familySupportCycle.findFirst({where:{familyId:family.id,status:'IN_PROGRESS'}}))error('A família já possui uma doação em andamento.',409,'family_cycle_blocked');const assignment=await tx.familyResponsibleAssignment.findFirst({where:{familyId:family.id,endedAt:null,responsibleUser:{status:'active',role:'beneficiary'}},select:{id:true}});const key=assignment&&await tx.directPixEvpKeyVersion.findFirst({where:{familyId:family.id,assignmentId:assignment.id,status:'ACTIVE'},select:{id:true}});if(!assignment||!key)error('Família indisponível para Pix direto.',409,'family_not_eligible');await assertDirectPixAvailable({familyId:family.id,entityId:family.entityId,keyVersionId:key.id,donorId:userId},tx);const idem=await tx.idempotencyRecord.create({data:{actorUserId:userId,operation:intentOperation,idempotencyKey:input.idempotencyKey,requestHash,status:'processing',expiresAt:new Date(Date.now()+TTL)}});const c=supportCycle(new Date());const created=await tx.directPixIntent.create({data:{donorId:userId,familyId:family.id,responsibleAssignmentId:assignment.id,pixKeyVersionId:key.id,amountCents:input.amountCents,txid:newTxid(),cycleStartAt:c.start,cycleEndAt:c.end,declarationDeadlineAt:new Date(Date.now()+TTL)}});await tx.auditLog.create({data:{actorUserId:userId,actorRole:'donor',action:'direct_pix.intent.created',entityType:'direct_pix_intent',entityId:created.id,channel:'web_pwa',correlationId:input.correlationId,idempotencyKey:input.idempotencyKey,result:'open',metadata:{familyId:family.id,amountCents:created.amountCents}}});await tx.idempotencyRecord.update({where:{id:idem.id},data:{resourceType:'direct_pix_intent',resourceId:created.id,status:'completed',completedAt:new Date()}});return created;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});return {intent:dto(x),replayed:false}; }

export async function createDisclosureGrant(userId:string,intentId:string) { const intent=await prisma.directPixIntent.findFirst({where:{id:intentId,donorId:userId,status:'OPEN',declarationDeadlineAt:{gt:new Date()}},include:{family:{select:{entityId:true}}}});if(!intent)error('Intenção indisponível.',404,'intent_not_found');if(!(await evaluateDirectPixFeature('DISCLOSURE',intent.familyId,intent.family.entityId)).enabled)error('Pix direto está temporariamente indisponível.',423,'direct_pix_disabled');await assertDirectPixAvailable({familyId:intent.familyId,entityId:intent.family.entityId,keyVersionId:intent.pixKeyVersionId,donorId:userId});const token=randomBytes(32).toString('base64url'),expiresAt=new Date(Date.now()+GRANT_TTL);await prisma.$transaction(async tx=>{await tx.pixDisclosureGrant.create({data:{intentId,actorUserId:userId,purpose:'donor_disclosure',tokenHash:tokenDigest(token),expiresAt}});await tx.directPixIntent.update({where:{id:intentId},data:{firstDisclosedAt:intent.firstDisclosedAt??new Date(),lastDisclosureExpiresAt:expiresAt}});await tx.auditLog.create({data:{actorUserId:userId,actorRole:'donor',action:'direct_pix.disclosure.granted',entityType:'direct_pix_intent',entityId:intentId,channel:'web_pwa',result:'granted',metadata:{expiresAt:expiresAt.toISOString()}}});});return {token,expiresAt:expiresAt.toISOString()}; }

export async function disclose(userId:string,intentId:string,token:string) { const grant=await prisma.pixDisclosureGrant.findFirst({where:{intentId,actorUserId:userId,purpose:'donor_disclosure',tokenHash:tokenDigest(token),revokedAt:null,expiresAt:{gt:new Date()}},include:{intent:{include:{family:true,pixKeyVersion:true}}}});if(!grant||grant.intent.status!=='OPEN')error('A revelação expirou ou é inválida.',410,'disclosure_expired');if(!(await evaluateDirectPixFeature('DISCLOSURE',grant.intent.familyId,grant.intent.family.entityId)).enabled||grant.intent.pixKeyVersion.status!=='ACTIVE')error('Pix direto está temporariamente indisponível.',423,'direct_pix_disabled');await assertDirectPixAvailable({familyId:grant.intent.familyId,entityId:grant.intent.family.entityId,keyVersionId:grant.intent.pixKeyVersionId,donorId:userId});const currentEnvelope = await prisma.directPixEvpKeyEnvelope.findFirst({ where: { keyVersionId: grant.intent.pixKeyVersion.id }, orderBy: { generation: 'desc' } }); const evp=decryptEvp(currentEnvelope ?? grant.intent.pixKeyVersion,{recordId:grant.intent.pixKeyVersion.id,familyId:grant.intent.familyId,assignmentId:grant.intent.responsibleAssignmentId,version:grant.intent.pixKeyVersion.version});const payload=buildStaticBrCode({evp,recipientName:grant.intent.family.responsibleName,city:grant.intent.family.city,amountCents:grant.intent.amountCents,txid:grant.intent.txid});await prisma.pixDisclosureGrant.update({where:{id:grant.id},data:{lastAccessedAt:new Date(),accessCount:{increment:1}}});return {pix:{keyType:'EVP',key:evp,recipientName:grant.intent.family.responsibleName},brCode:{format:'BR_CODE',payload,txid:grant.intent.txid,amountCents:grant.intent.amountCents},expiresAt:grant.expiresAt.toISOString()}; }

export async function declareSend(userId:string,intentId:string,input:{idempotencyKey:string;correlationId:string}) { const requestHash=digest({intentId});const old=await replay(userId,declarationOperation,input.idempotencyKey,requestHash);if(old)return {declarationId:old,replayed:true};const declared=await prisma.$transaction(async tx=>{const intent=await tx.directPixIntent.findFirst({where:{id:intentId,donorId:userId},include:{disclosureGrants:true}});if(!intent)error('Intenção não encontrada.',404,'intent_not_found');await tx.$executeRawUnsafe('SELECT pg_advisory_xact_lock(hashtext($1))','direct-pix-family:'+intent.familyId);if(intent.status!=='OPEN'||intent.declarationDeadlineAt<=new Date())error('A intenção não pode mais ser declarada.',410,'intent_expired');const idem=await tx.idempotencyRecord.create({data:{actorUserId:userId,operation:declarationOperation,idempotencyKey:input.idempotencyKey,requestHash,status:'processing',expiresAt:new Date(Date.now()+TTL)}});const now=new Date();let cycle=await tx.familySupportCycle.findUnique({where:{familyId_cycleStartAt:{familyId:intent.familyId,cycleStartAt:intent.cycleStartAt}}});if(!cycle){cycle=await tx.familySupportCycle.create({data:{familyId:intent.familyId,cycleStartAt:intent.cycleStartAt,cycleEndAt:intent.cycleEndAt,blockedAt:now}});await tx.directPixIntent.updateMany({where:{familyId:intent.familyId,status:'OPEN',disclosureGrants:{some:{createdAt:{lte:now},expiresAt:{gte:now}}}},data:{cycleId:cycle.id,cohortCapturedAt:now}});}if(!await tx.directPixIntent.findFirst({where:{id:intent.id,cycleId:cycle.id}}))error('A intenção não pertence à coorte congelada.',409,'intent_not_in_cohort');const declaration=await tx.directPixDeclaration.create({data:{intentId:intent.id,declaredByUserId:userId,declaredAt:now}});await tx.directPixIntent.update({where:{id:intent.id},data:{status:'DONOR_DECLARED',declaredAt:now,confirmationDeadlineAt:new Date(now.getTime()+172800000)}});await tx.auditLog.create({data:{actorUserId:userId,actorRole:'donor',action:'direct_pix.send.declared',entityType:'direct_pix_declaration',entityId:declaration.id,channel:'web_pwa',correlationId:input.correlationId,idempotencyKey:input.idempotencyKey,result:'in_progress',metadata:{intentId:intent.id,familyId:intent.familyId,cycleId:cycle.id}}});await tx.idempotencyRecord.update({where:{id:idem.id},data:{resourceType:'direct_pix_declaration',resourceId:declaration.id,status:'completed',completedAt:new Date()}});return declaration;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});return {declarationId:declared.id,replayed:false}; }
export async function publicProjection(familyId:string) { return {familyId,availability:(await prisma.familySupportCycle.findFirst({where:{familyId,status:'IN_PROGRESS'}}))?'IN_PROGRESS':'AVAILABLE'}; }
