import { createHash, randomBytes } from 'node:crypto';
import { Prisma, type DirectPixSuspensionScope } from '@prisma/client';
import { prisma } from '../../database/prisma';
import { AppError } from '../../shared/errors/AppError';
import { requireStepUpAuthorization } from '../auth/stepUp.service';
import { decryptEvp } from './evpKey.crypto';

const active = { revokedAt: null, OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }] } as const;
const code = /^[A-Z][A-Z0-9_]{2,63}$/;
function digest(value: string) { return createHash('sha256').update(value + ':' + process.env.JWT_SECRET).digest('hex'); }
export async function effectiveSuspension(input: { familyId: string; entityId: string | null; keyVersionId: string; donorId?: string; responsibleUserId?: string }, tx: Prisma.TransactionClient | typeof prisma = prisma) {
  const rows = await tx.directPixSuspension.findMany({ where: { revokedAt: null, AND: [{ OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }] }, { OR: [
    { scope: 'KEY', keyVersionId: input.keyVersionId }, { scope: 'FAMILY', familyId: input.familyId },
    ...(input.entityId ? [{ scope: 'ENTITY' as const, entityId: input.entityId }] : []),
    ...(input.donorId ? [{ scope: 'DONOR_ACCOUNT' as const, userId: input.donorId }] : []),
    ...(input.responsibleUserId ? [{ scope: 'RESPONSIBLE_ACCOUNT' as const, userId: input.responsibleUserId }] : [])
  ] } ] }, select: { scope: true } });
  return rows[0]?.scope ?? null;
}
export async function assertDirectPixAvailable(input: { familyId: string; entityId: string | null; keyVersionId: string; donorId?: string; responsibleUserId?: string }, tx?: Prisma.TransactionClient) {
  if (await effectiveSuspension(input, tx ?? prisma)) throw new AppError('Pix direto está temporariamente indisponível.', 423, 'direct_pix_suspended');
}
export async function suspendDirectPix(actorUserId: string, input: { scope: DirectPixSuspensionScope; targetId: string; reasonCode: string; expiresAt?: Date; correlationId: string }) {
  if (!code.test(input.reasonCode)) throw new AppError('Motivo de suspensão inválido.', 422, 'invalid_suspension_reason');
  return prisma.$transaction(async tx => {
    let target: { familyId?: string; entityId?: string | null; keyVersionId?: string; userId?: string; responsibleUserId?: string };
    if (input.scope === 'KEY') { const key = await tx.directPixEvpKeyVersion.findUnique({ where: { id: input.targetId }, select: { id: true, familyId: true, family: { select: { entityId: true } }, assignment: { select: { responsibleUserId: true } } } }); if (!key) throw new AppError('Recurso Pix direto não encontrado.',404,'direct_pix_resource_not_found'); target={keyVersionId:key.id,familyId:key.familyId,entityId:key.family.entityId,responsibleUserId:key.assignment.responsibleUserId}; await tx.directPixEvpKeyVersion.updateMany({where:{id:key.id,status:{in:['ACTIVE','PENDING_REVIEW','SECOND_APPROVAL_REQUIRED','AWAITING_RESPONSIBLE_CONFIRMATION']}},data:{status:'SUSPENDED'}}); }
    else if (input.scope === 'FAMILY') { const f=await tx.family.findUnique({where:{id:input.targetId},select:{id:true,entityId:true}});if(!f)throw new AppError('Recurso Pix direto não encontrado.',404,'direct_pix_resource_not_found');target={familyId:f.id,entityId:f.entityId}; await tx.directPixEvpKeyVersion.updateMany({where:{familyId:f.id,status:'ACTIVE'},data:{status:'SUSPENDED'}}); }
    else if (input.scope === 'ENTITY') { const e=await tx.entity.findUnique({where:{id:input.targetId},select:{id:true}});if(!e)throw new AppError('Recurso Pix direto não encontrado.',404,'direct_pix_resource_not_found');target={entityId:e.id}; }
    else { const u=await tx.user.findUnique({where:{id:input.targetId},select:{id:true}});if(!u)throw new AppError('Recurso Pix direto não encontrado.',404,'direct_pix_resource_not_found');target={userId:u.id}; }
    const row=await tx.directPixSuspension.create({data:{scope:input.scope,keyVersionId:target.keyVersionId,familyId:target.familyId,entityId:target.entityId ?? undefined,userId:target.userId,reasonCode:input.reasonCode,expiresAt:input.expiresAt,actorUserId}});
    const where = input.scope==='KEY'?{intent:{pixKeyVersionId:target.keyVersionId}}:input.scope==='FAMILY'?{intent:{familyId:target.familyId}}:input.scope==='ENTITY'?{intent:{family:{entityId:target.entityId}}}:{actorUserId:target.userId};
    await tx.pixDisclosureGrant.updateMany({where:{...where,revokedAt:null},data:{revokedAt:new Date()}});
    await tx.stepUpAuthorization.updateMany({where:{revokedAt:null,OR:[...(target.familyId?[{resourceId:target.familyId}]:[]),...(target.userId?[{userId:target.userId}]:[])]},data:{revokedAt:new Date()}});
    await tx.directPixBreakGlassGrant.updateMany({where:{revokedAt:null, ...(target.keyVersionId?{keyVersionId:target.keyVersionId}:target.familyId?{keyVersion:{familyId:target.familyId}}:target.entityId?{keyVersion:{family:{entityId:target.entityId}}}:target.userId?{keyVersion:{assignment:{responsibleUserId:target.userId}}}:{})},data:{revokedAt:new Date()}});
    await tx.auditLog.create({data:{actorUserId,actorRole:'admin',action:'direct_pix.suspension.created',entityType:'direct_pix_suspension',entityId:row.id,channel:'admin_api',correlationId:input.correlationId,result:'suspended',metadata:{scope:input.scope,reasonCode:input.reasonCode,expiresAt:input.expiresAt?.toISOString()??null}}});
    return {id:row.id,scope:row.scope,expiresAt:row.expiresAt?.toISOString()??null};
  },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
}
export async function createBreakGlassGrant(actorUserId:string,keyVersionId:string,input:{purposeCode:string;stepUpAuthorization:string;correlationId:string}) { if(!code.test(input.purposeCode))throw new AppError('Propósito inválido.',422,'invalid_break_glass_purpose'); return prisma.$transaction(async tx=>{await requireStepUpAuthorization({userId:actorUserId,token:input.stepUpAuthorization,purpose:'break_glass_evp',resourceId:keyVersionId,consume:true,client:tx}); const key=await tx.directPixEvpKeyVersion.findUnique({where:{id:keyVersionId},select:{id:true}});if(!key)throw new AppError('Recurso Pix direto não encontrado.',404,'direct_pix_resource_not_found');const token=randomBytes(32).toString('base64url'),expiresAt=new Date(Date.now()+5*60_000);const grant=await tx.directPixBreakGlassGrant.create({data:{actorUserId,keyVersionId,purposeCode:input.purposeCode,tokenHash:digest(token),correlationId:input.correlationId,expiresAt}});await tx.auditLog.create({data:{actorUserId,actorRole:'admin',action:'direct_pix.break_glass.granted',entityType:'direct_pix_break_glass_grant',entityId:grant.id,channel:'admin_api',correlationId:input.correlationId,result:'granted',metadata:{keyVersionId,purposeCode:input.purposeCode,expiresAt:expiresAt.toISOString()}}});return {token,expiresAt:expiresAt.toISOString()};}); }
export async function consumeBreakGlass(actorUserId:string,keyVersionId:string,token:string) { return prisma.$transaction(async tx=>{const g=await tx.directPixBreakGlassGrant.findUnique({where:{tokenHash:digest(token)}});if(!g||g.actorUserId!==actorUserId||g.keyVersionId!==keyVersionId||g.revokedAt||g.consumedAt||g.expiresAt<=new Date()){await tx.auditLog.create({data:{actorUserId,actorRole:'admin',action:'direct_pix.break_glass.denied',entityType:'direct_pix_evp_key_version',entityId:keyVersionId,channel:'admin_api',result:'denied',metadata:{reasonCode:'INVALID_OR_EXPIRED'}}});throw new AppError('Acesso emergencial indisponível.',401,'break_glass_denied');} const changed=await tx.directPixBreakGlassGrant.updateMany({where:{id:g.id,consumedAt:null,revokedAt:null,expiresAt:{gt:new Date()}},data:{consumedAt:new Date()}});if(!changed.count)throw new AppError('Acesso emergencial indisponível.',401,'break_glass_denied');const key=await tx.directPixEvpKeyVersion.findUniqueOrThrow({where:{id:keyVersionId,},include:{envelopes:{orderBy:{generation:'desc'},take:1}}});const envelope=key.envelopes[0]??key;const evp=decryptEvp(envelope,{recordId:key.id,familyId:key.familyId,assignmentId:key.assignmentId,version:key.version});await tx.auditLog.create({data:{actorUserId,actorRole:'admin',action:'direct_pix.break_glass.used',entityType:'direct_pix_break_glass_grant',entityId:g.id,channel:'admin_api',correlationId:g.correlationId,result:'used',metadata:{keyVersionId,purposeCode:g.purposeCode}}});return {keyType:'EVP',key:evp};}); }
